### ISSUE TITLE
virtual-manager fails after upgrading to glib2.0 2.89.3

### ISSUE THREAD

**Issue by texstar** [virt-manager/virt-manager#1129]
virt-manager 5.1.0 fails to launch after updating glib2.0 to 2.89.3 with the following output.

Erreur lors du démarrage du Gestionnaire de Machines Virtuelles : 'gi.repository.GLib' object has no attribute 'unix_signal_add'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 312, in runcli
    main()
    ~~~~^^
  File "/usr/share/virt-manager/virtManager/virtmanager.py", line 305, in main
    GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGINT, _sigint_handler, None)
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/site-packages/gi/overrides/__init__.py", line 31, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib64/python3.13/site-packages/gi/module.py", line 130, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
                         self.__name__, name))
AttributeError: 'gi.repository.GLib' object has no attribute 'unix_signal_add'

**Comment by phrdina** [comment]
What distribution are you using? I just tested it using Fedora Rawhide where there is glib2.0 2.89.3 and virt-manager starts without any issue.

**Comment by texstar** [comment]
We are using PCLinuxOS. I guess it is on us to fix since it works for you. Thanks for checking. I will go look for patches and compare our builds with fedora rawhide.

**Comment by texstar** [comment]
I was able to fix it by editing a couple of lines in /usr/share/virt-manager/virtManager/virtmanager.py.
