### ISSUE TITLE
Fails to build with libvirt 8.1.0

### ISSUE THREAD

**Issue by Fantu** [virt-manager/virt-manager#382]
Hi, there is a fails to build spotted by debian reproducible-builds, virt-manager 4.0.0 was build correctly with libvirt 8.0.0 (at the time of upload to unstable), after the upload of libvirt 8.1.0 fails to build, more exactly fails the test part.

```
=========================== short test summary info ============================
SKIPPED [165] tests/utils.py:134: error opening testdriver.xml: unsupported configuration: unfiltered sgio is no longer supported
libvirt is probably too old
SKIPPED [2] tests/test_checkprops.py:15: Other tests failed or were skipped, don't do prop checks
================= 2 failed, 372 passed, 167 skipped in 20.03s ==================
```
Full build log:
https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/virt-manager.html

From a fast look I don't see commit or PR that fix it for now

**Comment by crobinso** [comment]
Thanks for the report, fixed in git now

**Comment by crobinso** [comment]
I missed a case, it needed a second commit. Just FYI if you are backporting patches

**Comment by Fantu** [comment]
@crobinso thanks for the fix and report that a second commit is needed
